### ISSUE TITLE
初期テキストエリアの明朝体を除去

### ISSUE THREAD

**Issue by qrac** [qrac/qroko#20]
![image](https://user-images.githubusercontent.com/9658016/86526990-7779bd80-bed5-11ea-8a3f-ed33e713f814.png)

ページ新規作成時のテキストエリア（Placeholder）が明朝体なのでゴシック体にする。

```css
.block-editor-default-block-appender textarea.block-editor-default-block-appender__content {
  font-family: "Noto Serif",serif;
}
```
